version: '2'
services:
    dora-app:
        image: dora
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://luulpos-mysql:3306/dora?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://luulpos-elasticsearch:9200
        ports:
            - 8080:8080
    dora-mysql:
        extends:
            file: mysql.yml
            service: dora-mysql
    dora-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: dora-elasticsearch
